version: "3"
services:
  repo:
    image: dnviti/fdroid-reposerver
    restart: always
    environment:
      - TZ=Europe/Rome
    ports:
      - 8083:80
      - 8084:8084
    build:
      context: .
      dockerfile: Dockerfile
