version: "3"
services:
  repo:
    image: dnviti/fdroid-reposerver
    restart: always
    environment:
      - TZ=Europe/Rome
    volumes:
      - fdroid:/fdroid
      - filebrowser:/database
    ports:
      - ${WEB_PORT-8083}:80
      - ${REPO_PORT-8084}:8084
volumes:
  filebrowser:
  fdroid:
